### PR TITLE
Automate Docker Builds + Minor README Improvement

### PR DESCRIPTION
**Pull request by wolveix**
Minorly cleaned up the README. Changed the docker-compose referencing to use the official Docker Hub image. Also included a Github Actions workflow to automate Docker builds, though you should modify it to include an additional push to the official Docker Hub repo.

### CODE REVIEW

**Comment by wolveix** [comment]
@MihkelBaranov Any chance this can get merged? 😃

**Comment by MihkelBaranov** [comment]
Looks good but I already have automated docker builds set up so it seems a bit redundant to also enable GitHub actions to do the same thing

**Comment by wolveix** [comment]
Fair enough! I've removed the GitHub Actions part of the PR :)

**Comment by MihkelBaranov** [comment]
@Wolveix have you joined our discord?

https://discord.gg/hqxATH

**Comment by wolveix** [comment]
@MihkelBaranov I have not, though I would be happy to. That invite link doesn't work, unfortunately.

**Comment by MihkelBaranov** [comment]
My bad, try this instead https://discord.gg/Ue85fEQ

**Pull request merged**
